# Generated by Django 3.0 on 2019-12-15 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_userform'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='pub_date',
        ),
    ]
